# Generated by Django 2.2.6 on 2019-10-27 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('published', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
